Task 10
pawkal1996/AvinGame2D pull request #21
Opened 2018-12-10 20:16 UTC by pawkal1996

ready to check

2018-12-10 20:17 UTC, lukasmaj commented on src/AvinGame.java
> +
Code style: remove blank lines

2018-12-10 20:18 UTC, lukasmaj commented on src/items/Armor.java
> +		armor1 = new Armor("�elazna zbroja", 10);
polish characters

2018-12-10 20:18 UTC, lukasmaj commented on src/items/Armor.java
> +	private int defense;
declare a top of class

2018-12-10 20:20 UTC, lukasmaj commented on src/items/Gold.java
> +	static Gold gold100;
access modificator

2018-12-10 20:21 UTC, lukasmaj commented on src/items/Sword.java
> +
remove blank lines

2018-12-10 20:22 UTC, lukasmaj commented on src/AvinGame.java
needed short description of classes.

2018-12-10 20:37 UTC, lukasmaj commented
Binary files aren't needed.
you must do this steps:
[on your branch]
git rm -r bin --cached
[on master]
git pull origin master
git rm -r bin --cached
git add .
git commit -m "rm binary files"
git push origin master
[on your branch]
git rm -r bin --cached
git add .
git commit -m "rm b..."
git merge origin/master
git push origin yourbranch

2018-12-10 20:39 UTC, lukasmaj commented on src/items/Gold.java
> +	static Gold gold150;
isn't issue, but why you use "recursive" variable?
what do this class?

2018-12-10 20:49 UTC, lukasmaj commented on src/items/Item.java
> +		Gold.createGold();
i need explanation

2018-12-10 20:49 UTC, lukasmaj commented on src/items/MagicBox.java
> +		magicBoxDrop.add(Sword.sword1);
don't looks good. I think that will be better when sword1, sword2 etc you will change to array.

2018-12-10 20:49 UTC, lukasmaj commented on src/items/Sword.java
> +	private int attack;
move to top of class

2018-12-10 20:49 UTC, lukasmaj commented on src/items/Armor.java
> +	static Armor armor1;
maybe array?

2018-12-10 20:57 UTC, pawkal1996 commented on src/AvinGame.java
> +
corrected

2018-12-10 20:57 UTC, pawkal1996 commented on src/items/Armor.java
> +		armor1 = new Armor("�elazna zbroja", 10);
corrected

2018-12-10 20:58 UTC, pawkal1996 commented on src/items/Armor.java
> +	private int defense;
corrected

2018-12-10 21:07 UTC, pawkal1996 commented on src/items/Gold.java
> +	static Gold gold100;
corrected

2018-12-10 21:07 UTC, pawkal1996 commented on src/items/Sword.java
> +
corrected

2018-12-10 21:13 UTC, pawkal1996 commented on src/AvinGame.java
corrected

2018-12-11 20:15 UTC, lukasmaj commented on src/items/Armor.java
> +	public static ArrayList<Armor> getArmors() {
why armors list is returned?
is needed?

2018-12-11 20:15 UTC, lukasmaj commented on src/items/Sword.java
> +		return swords;
why sword list is returned?

2018-12-11 20:15 UTC, lukasmaj commented on src/items/Gold.java
> +		this.name = "Gold";
is needed?

2018-12-11 20:15 UTC, lukasmaj commented on src/items/Armor.java
> +	private static ArrayList<Armor> armors = new ArrayList<>();
will be better when variables will be initialize in constructor.

2018-12-11 20:15 UTC, lukasmaj commented on src/items/MagicBox.java
> +	private static ArrayList<Item> magicBoxDrop = new ArrayList<Item>();
same as up

2018-12-11 20:15 UTC, lukasmaj commented on src/items/Sword.java
> +	private static ArrayList<Sword> swords = new ArrayList<>();
else this

2018-12-11 20:15 UTC, lukasmaj commented on src/items/MagicBox.java
> +
empty line

2019-01-14 14:43 UTC, pawkal1996 commented on src/items/Armor.java
> +	public static ArrayList<Armor> getArmors() {
because you need this list to rand one of them in MagicBox class

2019-01-14 16:02 UTC, lukasmaj requested changes

2019-01-14 16:02 UTC, lukasmaj commented on src/items/Armor.java
> +		Armor.armors = armors;
i'm not sure if it will works. Probably you assigned pointer instead of values. You must check it. 
setArmors(someArmors);
In case above sobeArmors and Armor.armors will be indicade a that same memory adress.

2019-01-14 16:02 UTC, lukasmaj commented on src/items/Gold.java
> +		gold.add(new Gold(100));
You shouldn't use naked numbers.
Will be better:
final int defaultNumberOfGold = 100;
new Gold(defaultNumberOfGold )

2019-01-14 16:02 UTC, lukasmaj commented on src/items/Sword.java
> +		swords.add(new Sword("�elazny sztylet", 10));
polish characters

2019-01-14 20:31 UTC, merged